### PR TITLE
Update example notebook Prediction with PyLogit from pd.Series.sort() to pd.Series.sort_values()

### PR DESCRIPTION
**Pull request by danhphan**
Change file /examples/notebooks/Prediction with PyLogit.ipynb: 
From:
```
pd.Series(prediction_log_likelihoods,
          name="Log-likelihood of Predictions").sort(inplace=False)
```
To:

```
pd.Series(prediction_log_likelihoods,
          name="Log-likelihood of Predictions").sort_values(inplace=False)
```
As both .sort() and order() functions are DEPRECATED
.sort_values() function is the replacement and here's the example on how to use it

Source: https://stackoverflow.com/questions/24049509/why-calling-sort-function-on-pandas-series-sorts-its-values-in-place-and-retu

### CODE REVIEW

**Review by timothyb0912 — CHANGES_REQUESTED** [review]
Hey @danhphan thanks so much for this.

It's a great reminder that the example notebooks need a formal maintenance process,
and / or they need to get included in integration tests.

Also, sorry about the lack of a CONTRIBUTING.md file to provide some guidance.
To start, can you

- [x] point your PR at Pylogit's  `develop` branch?
I use git-flow for branching, so I merge to master only from `develop`.
- [x] add a [newsfragment](https://towncrier.readthedocs.io/en/actual-freaking-docs/quickstart.html#creating-news-fragments) describing your change to the newsfragments [directory](https://github.com/timothyb0912/pylogit/tree/master/src/pylogit/newsfragments)?
You can view the set of newsfragment types [here](https://github.com/timothyb0912/pylogit/blob/master/pyproject.toml#L48)
and you can see examples of previous newsfragments [here](https://github.com/timothyb0912/pylogit/tree/develop/src/pylogit/newsfragments).

I'll merge your changes quickly after these changes,
and after I actually view the notebook /
compute a more helpful notebook diff than the github defaults.

Thanks again!

**Comment by danhphan** [comment]
Hi @timothyb0912, thank you for the information. I have changed the branch to develop, and add a newsfragment named 72.trivial. If it is not a right way, just let me know :)

The notebook examples are great, I have run all of them and they are all good. I may add some more small examples (such as calculate accuracy, f1-score) soon, so new users can use them to compare discrete choice models with other kinds of models on these metrics.

Thank you.

**Comment by timothyb0912** [comment]
@danhphan, thanks for checking all of the example notebooks 🙏🏽 .

The way you added the newsfragment is correct, and the notebook looks good to me.
I should have pointed out that the identifier is the PR id.
Sorry about that!

Can you remove newsfragment 69 since it's not needed / misleading?

The examples you have planned sound great, and I'd be happy to have them!
Send the PR(s) whenever you're ready.

I'll merge this once fragment 69 is removed.

**Comment by danhphan** [comment]
Hi @timothyb0912, I have removed the fragment 69. Thank you 👍

**Review by timothyb0912 — APPROVED** [review]
👍🏽 No problem, thanks again for your contribution @danhphan!

**Pull request merged**
